<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
	<link rel="stylesheet" type="text/css" href="css/style.css" />
	<title>Newsletter</title>
</head>

<body>
	<h1>RADIOHEAD</h1>
	<hr />
	<div id="navi">
		<ul id="navigation">
			<li><a href="index.html">HOME</a></li>
			<li><a href="history.html">HISTORY</a></li>
			<li><a href="members.html">MEMBERS</a></li>
			<li><a href="discography.html">DISCOGRAPHY</a></li>
			<li><a href="links.html">LINKS</a></li>
			<li><strong><a href="#">NEWSLETTER</a></strong></li>
		</ul>
	</div>
	
	<div id="maincontent">
		<h2>NEWSLETTER</h2>
		<p>Want to keep up with the latest news, tour dates and CD releases? Sign up to our website 
			and you can receive our weekly email newsletter!</p>
			<a href="http://el.wikipedia.org/"><img class="centre" src="images/radiohead-portugal.jpg" title="Radiohead in Portugal" alt="Radiohead in Portugal" /></a>
			<p class="center">Click <a href="php/member.php" title="Members">here</a> to change your preferences.</p>
		
		<p class="center"><a href="php/signup.php" title="signup">Sign Up</a>&nbsp;|&nbsp;<a href="php/login.php" title="Login">Login</a></p>
	</div>
	
	<hr />
	<div id="footer">
		<p>Copyright Nick Playfair &copy; 2009. Images licensed under 
			Creative Commons ShareAlike and Attribution Licenses.</p>
		<p>
		<a href="http://validator.w3.org/check?uri=referer">
		<img src="images/xhtml10.png" alt="Valid XHTML 1.0 Strict" /></a>
		&nbsp;
		<a href="http://jigsaw.w3.org/css-validator/check/referer">
		<img src="images/css.png"
		alt="Valid CSS!" /></a>
		</p>
	</div> 
</body>
</html>